# Generated by Django 3.0.8 on 2020-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=20, null=True, verbose_name='手机号码'),
        ),
    ]
